name: Souso - CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Souso - CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --no-daemon

      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Publish to Souso Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: souso
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          tags: latest
          build-args: |
            JDBC_URL=${{ secrets.JDBC_URL }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PWD=${{ secrets.DB_PWD }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            COOLSMS_API_KEY=${{ secrets.COOLSMS_API_KEY }}
            COOLSMS_SECRET_KEY=${{ secrets.COOLSMS_SECRET_KEY }}
            COOLSMS_PHONE_NUMBER=${{ secrets.COOLSMS_PHONE_NUMBER }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            AWS_REGION=${{ secrets.AWS_REGION }}

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: Elastic Beanstalk Souso Application Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Souso-Server
          environment_name: Sousoserver-env
          version_label: Souso-${{steps.current-time.outputs.formattedTime}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: Docker.aws.json
          wait_for_environment_recovery: 120
